### ISSUE TITLE
issues for everyone willing to spend time and actually patch bolt's app and try this:

### ISSUE THREAD

**Issue by jj15warrior** [amstrdm/Bolt4Free#17]
1. this code only works in germany (or is not up to date with api changes?)
2. from what i found the api is not under germany-rental.taxify.eu even for germany (however i'm not sure if i can disclose this - it's easy to find it)

**Comment by amstrdm** [comment]
The code used to work outside of Germany. However, I stopped keeping up with API changes because the vulnerability was patched. Bolt was notified and they have since changed their payment structure so that the vulnerability isn't applicable anymore. The API was under germany-rental.taxify.eu when I first developed this script btw. 
In case anyone should come up with how the Approach I used for this vulnerability could be adjusted to account for Bolt's new payment structure please let me know. I will start updating the codebase again to be on track with the current state of the API. Until then the idea for this specific vulnerability was patched and this repo now serves as a POC.

**Comment by jj15warrior** [comment]
i recreated your code and it looks like they first lock some currency (10 PLN in my case) and then return what you haven't used. Even if that wasn't the case, they now charge even for one second of riding. There is no free cancellation period that we could abuse, so this method is not applicable. One cool thing i found is that 
1. you can make any scooter ring anywhere in the world, and with a script this would be funny. 
2. there is a way to get scooter uuid from it's id by using the /ring request

**Comment by jj15warrior** [comment]
one more cool thing that i haven't tested in practice yet: there is a secret speed mode outside comfort and safe, idk if it works

**Comment by amstrdm** [comment]
Yes, that was exactly what  I was talking about the locking up of payment and the charging by the second fixed this vulnerability. The /ring endpoint must be new back when I developed this script I had to write a separate script to first reserve a scooter, which made it possible to get the first three digits of the uuid and then brute force the last three.
